<?php
# null=noMOSTRAR  ALL_ERROR WARNINGS 
error_reporting(null);
# 0=NOMOSTRARERRORES 1=MOSTRARERRORES
ini_set('display_errors', 0);
# NOMBRE DEL SISTEMA OPERATIVO LINUX O WINDOWS
$VARIABLE["SISTEMAOPERATIVO"]="LINUX"; 
# NOMBRE DE LA IMPRESORA DENTRO DEL SISTEMA OPERATIVO
$VARIABLE["NOMBREIMPRESORA"]="EPSON_TM-T20II";
# PARA DEFINIR LA ACCION A REALIZAR DESPUES DE IMPRIMIR EL TICKET 
$VARIABLE["ALCARGAR"]=" onload='javascript:window.close()' "; // CERRAR
$VARIABLE["ALCARGAR"]="  "; // NO CERRAR
?>