<?php
# RECEPCION DE DATOS VIA POST
echo "<br>EMISOR_RAZONSOCIAL=".$VARIABLE["EMISOR_RAZONSOCIAL"]=trim($_POST["EMISOR_RAZONSOCIAL"]);
echo "<br>FOLIONV=".$VARIABLE["FOLIONV"]=trim($_POST["FOLIONV"]);
echo "<br>ITEMS=".$VARIABLE["ITEMS"]=trim($_POST["ITEMS"]);
echo "<br>FECHAEMISION=".$VARIABLE["FECHAEMISION"]=trim($_POST["FECHAEMISION"]);
echo "<br>HORAEMISION=".$VARIABLE["HORAEMISION"]=trim($_POST["HORAEMISION"]);
echo "<br>EANNV=".$VARIABLE["EANNV"]=trim($_POST["EANNV"]);
echo "<br>TOTALES_BRUTO=".$VARIABLE["TOTALES_BRUTO"]=trim($_POST["input_total"]);
echo "<br>VENDEDOR=".$VARIABLE["VENDEDOR"]=trim($_POST["VENDEDOR"]);
?>